// Manager main window
// Original code generated by QT Designer 2.0 for QT 3.0.2
// (c) 2002 Ilkka Karvinen

#ifndef MANAGERMAIN_H
#define MANAGERMAIN_H

#include "agentlist.h"
#include <qvariant.h>
#include <qmainwindow.h>
class QVBoxLayout; 
class QHBoxLayout; 
class QGridLayout; 
class QAction;
class QActionGroup;
class QToolBar;
class QPopupMenu;
class QListView;
class QListViewItem;
class QPushButton;

class ManagerMain : public QMainWindow
{ 
    Q_OBJECT

public:
    ManagerMain( QWidget* parent = 0, const char* name = 0, 
		 WFlags fl = WType_TopLevel );
    ~ManagerMain();

    AgentList* agentList;
    QPushButton* SelectButton;
    QPushButton* UpdateButton;
    QMenuBar *menubar;
    QPopupMenu *fileMenu;
    QPopupMenu *helpMenu;
    QAction* fileExitAction;
    QAction* helpAboutAction;


public slots:
    virtual void fileExit();
    virtual void helpAbout();
    virtual void selectSlot();

protected:
    QVBoxLayout* ManagerMainLayout;
    QVBoxLayout* VerticalLayout;
    QHBoxLayout* HorizontalLayout;

};

#endif // MANAGERMAIN_H
