#ifndef MANAGER_ICONS_H
#define MANAGER_ICONS_H

/* XPM */
static const char *sm_happy[] = {
/* width height num_colors chars_per_pixel */
"    16    16        4            1",
/* colors */
". c #009c00",
"# c #00ce00",
"a c #ffffff",
"b c #000000",
/* pixels */
"aaaaabbbbbaaaaaa",
"aaabb.....bbaaaa",
"aab..#####..baaa",
"ab.#########.baa",
"ab.#bb.#.bb#.baa",
"b.##bb.#.bb##.ba",
"b.##..###..##.ba",
"b.###########.ba",
"b.###########.ba",
"b.##b#####b##.ba",
"ab.##bbbbb##.baa",
"ab.#########.baa",
"aab..#####..baaa",
"aaabb.....bbaaaa",
"aaaaabbbbbaaaaaa",
"aaaaaaaaaaaaaaaa"
};

/* XPM */
static const char *sm_unhappy[] = {
/* width height num_colors chars_per_pixel */
"    16    16        4            1",
/* colors */
". c #ff0000",
"# c #ff1800",
"a c #ffffff",
"b c #000000",
/* pixels */
"aaaaabbbbbaaaaaa",
"aaabb.....bbaaaa",
"aab..#####..baaa",
"ab.#########.baa",
"ab.#bb.#.bb#.baa",
"b.##bb.#.bb##.ba",
"b.##..###..##.ba",
"b.###########.ba",
"b.###########.ba",
"b.###########.ba",
"ab.##bbbbb##.baa",
"ab.#b#####b#.baa",
"aab..#####..baaa",
"aaabb.....bbaaaa",
"aaaaabbbbbaaaaaa",
"aaaaaaaaaaaaaaaa"
};

/* XPM */
static const char *greenball[] = {
/* width height num_colors chars_per_pixel */
"    14    14       42            1",
/* colors */
". c #ffffff",
"# c #0f721b",
"a c #31ff45",
"b c #10ce28",
"c c #00620f",
"d c #308b3e",
"e c #00bc18",
"f c #7ac583",
"g c #00bc1b",
"h c #00e61e",
"i c #00de1e",
"j c #7ac586",
"k c #00fd1d",
"l c #0fff2f",
"m c #62cd74",
"n c #006a0d",
"o c #005a0d",
"p c #004a0d",
"q c #009c16",
"r c #00c619",
"s c #009416",
"t c #00ac19",
"u c #4a9c55",
"v c #00d61c",
"w c #08d627",
"x c #8fff8b",
"y c #00ce1f",
"z c #21ff3f",
"A c #005a08",
"B c #004a08",
"C c #10841e",
"D c #b1ffa5",
"E c #07ff28",
"F c #00fd21",
"G c #00720e",
"H c #0fff33",
"I c #008411",
"J c #00b41a",
"K c #42ce54",
"L c #00ee23",
"M c #bcc5bf",
"N c #62cd70",
/* pixels */
"..............",
"..............",
"....jKbbKj....",
"...mvkkFLrm...",
"..fyklaEhrqf..",
"..KkExDHvesC..",
"..bFEazweqIo..",
"..bihiyJqIco.M",
"..KeegtqIAB#M.",
"..fsqsIGcpBu..",
"...NnnoBBBd...",
"..M.f#oo#uM...",
"....M...M..M..",
".....M...M..M."
};

/* XPM */
static const char *redball[] = {
/* width height num_colors chars_per_pixel */
"    14    14       42            1",
/* colors */
". c #ffffff",
"# c #940028",
"a c #4a0017",
"b c #c57a93",
"c c #c60038",
"d c #ff0f59",
"e c #720020",
"f c #ce1049",
"g c #ee0041",
"h c #ff2162",
"i c #9c0028",
"j c #ff8bd5",
"k c #720f30",
"l c #4a000f",
"m c #c57a8b",
"n c #ce0038",
"o c #ff0f51",
"p c #c5bcbc",
"q c #ff0751",
"r c #9c4a62",
"s c #ac0030",
"t c #841030",
"u c #5a0017",
"v c #fd0051",
"w c #cd627a",
"x c #ff317a",
"y c #5a0020",
"z c #bc0038",
"A c #d60841",
"B c #b40030",
"C c #d60041",
"D c #620017",
"E c #840028",
"F c #ce426a",
"G c #8b3049",
"H c #cd6283",
"I c #fd0049",
"J c #bc0030",
"K c #de0041",
"L c #ffa5ee",
"M c #e60041",
"N c #6a0020",
/* pixels */
"..............",
"..............",
"....mFffFm....",
"...wCvvIgcw...",
"..bnvdxqMcib..",
"..FvqjLoCz#t..",
"..fIqxhAziEu..",
"..fKMKnBiEDu.p",
"..FzzJsiEyakp.",
"..b#i#EeDlar..",
"...HNNuaaaG...",
"..p.bkuukrp...",
"....p...p..p..",
".....p...p..p."
};

/* XPM */
static const char *fileicon[] = {
/* columns rows colors chars-per-pixel */
"16 16 10 1",
"' c #000000000000",
". c #303030303030",
"X c #585858585858",
"o c #a0a0a0a0a0a0",
"O c #ffffdcdca8a8",
"+ c #c3c3c3c3c3c3",
"@ c #dcdcdcdcdcdc",
"# c #ffffffffc0c0",
"$ c #ffffffffffff",
"  c None",
/* pixels */
"  XXXXX..''     ",
"  X@@@@@+.+'    ",
"  X@$$$$$X$@'   ",
"  X@'$'$$X@$+'  ",
"  X@$$$$$XXX.'  ",
"  X@'$'$$$@+o'  ",
"  X@$$$$$$#$@'  ",
"  X@$$'$'$'$$'  ",
"  X@$$$$#$#$#'  ",
"  X@'$'$$$'O$'  ",
"  X@$$#$#$#$#'  ",
"  X@'$'$'O'O$'  ",
"  X@#$#$#$#$#'  ",
"  X@$$$O$O$O#'  ",
"  X@#$#$#$###'  ",
"  .'''''''''''  ",
};

/* XPM */
static const char *folder[]={
"16 16 9 1",
"g c #808080",
"b c #ffa858",
"e c #c0c0c0",
"# c #000000",
"c c #ffdca8",
". c None",
"a c #585858",
"f c #a0a0a4",
"d c #ffffff",
"..#a#...........",
".#abc##.........",
".#daabc#####....",
".#ddeaabcccb#...",
".#dedeeabccca...",
".#edeeeeaaaab#..",
".#deeeeeeefe#ba.",
".#eeeeeeefef#ba.",
".#eeeeeefeff#ba.",
".#eeeeefefff#ba.",
".##geefeffff#ba.",
"...##gefffff#ba.",
".....##fffff#ba.",
".......##fff#b##",
".........##f#b##",
"...........####."};

/* XPM */
static const char *folder_open[]={
"16 16 11 1",
"# c #000000",
"g c #c0c0c0",
"e c #303030",
"a c #ffa858",
"b c #808080",
"d c #a0a0a4",
"f c #585858",
"c c #ffdca8",
"h c #dcdcdc",
"i c #ffffff",
". c None",
"....###.........",
"....#ab##.......",
"....#acab####...",
"###.#acccccca#..",
"#ddefaaaccccca#.",
"#bdddbaaaacccab#",
".eddddbbaaaacab#",
".#bddggdbbaaaab#",
"..edgdggggbbaab#",
"..#bgggghghdaab#",
"...ebhggghicfab#",
"....#edhhiiidab#",
"......#egiiicfb#",
"........#egiibb#",
"..........#egib#",
"............#ee#"};

static const char * folder_locked[]={
    "16 16 10 1",
    "h c #808080",
    "b c #ffa858",
    "f c #c0c0c0",
    "e c #c05800",
    "# c #000000",
    "c c #ffdca8",
    ". c None",
    "a c #585858",
    "g c #a0a0a4",
    "d c #ffffff",
    "..#a#...........",
    ".#abc####.......",
    ".#daa#eee#......",
    ".#ddf#e##b#.....",
    ".#dfd#e#bcb##...",
    ".#fdccc#daaab#..",
    ".#dfbbbccgfg#ba.",
    ".#ffb#ebbfgg#ba.",
    ".#ffbbe#bggg#ba.",
    ".#fffbbebggg#ba.",
    ".##hf#ebbggg#ba.",
    "...###e#gggg#ba.",
    ".....#e#gggg#ba.",
    "......###ggg#b##",
    ".........##g#b##",
    "...........####."};

static const char * pix_file []={
    "16 16 7 1",
    "# c #000000",
    "b c #ffffff",
    "e c #000000",
    "d c #404000",
    "c c #c0c000",
    "a c #ffffc0",
    ". c None",
    "................",
    ".........#......",
    "......#.#a##....",
    ".....#b#bbba##..",
    "....#b#bbbabbb#.",
    "...#b#bba##bb#..",
    "..#b#abb#bb##...",
    ".#a#aab#bbbab##.",
    "#a#aaa#bcbbbbbb#",
    "#ccdc#bcbbcbbb#.",
    ".##c#bcbbcabb#..",
    "...#acbacbbbe...",
    "..#aaaacaba#....",
    "...##aaaaa#.....",
    ".....##aa#......",
    ".......##......."};

#endif

